- name: Run ACME tests
  hosts: host
  tasks:
  - import_tasks: test-setup.yml
  - import_tasks: test-account-setup.yml
  - import_tasks: test-certificate.yml
  - import_tasks: test-account.yml
  - import_tasks: test-account-validate.yml
