- name: Run ACME tests
  hosts: localhost
  tasks:
  - name: store the ACME container hostname
    set_fact:
      acme_host: "{{ lookup('env', 'acme_host') }}"
  - import_tasks: test-setup.yml
  - import_tasks: test-account-setup.yml
  - import_tasks: test-certificate.yml
  - import_tasks: test-account.yml
  - import_tasks: test-account-validate.yml
